version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - rede
    ports:
      - '9090:9090'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    networks:
      - rede
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - cache:/data
volumes:
  grafana_data:
  prometheus_data:
  cache:
    driver: local

networks:
  rede:
    driver: bridge
