server:
  port: 8081
spring:
  application:
    name: Volunteer Accessory Api
  datasource:
    url: "jdbc:h2:file:~/dados/volunteer-accessory-api"
    username: "sa"
    password: "sa"
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
