server:
  port: 8080
spring:
  application:
    name: Volunteer Accessory Api
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days