server:
  port: 8080
spring:
  application:
    name: Volunteer Accessory Api
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: "password"
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs.html
