on:
  pull_request:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: phelliperodrigues/volunteer-accessory-api
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and run tests
        run: |
          mvn test -Ptest  -Dspring.profiles.active=test
      - name: Send Slack notification on failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          APP_NAME: ${{ github.event.repository.name }} # Nome do repositório Git (app)
          PR_TITLE: |
            ${{ github.event.pull_request.title }}  PR: #${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.name }}
          PIPE_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\":x:\nFail Deploy\n*Job*:test\n*Repository*: ${APP_NAME}\n*Author*:${PR_AUTHOR}\n*Commit/PR*:${PR_TITLE}\n*Action*:${PIPE_URL}\"}" $SLACK_WEBHOOK_URL

  notify-result:
    name: Notify Result on Slack
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Send Slack notification on success
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          APP_NAME: ${{ github.event.repository.name }} # Nome do repositório Git (app)
          PR_TITLE: |
            ${{ github.event.pull_request.title }}  PR: #${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.name }}
          PIPE_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          PR_NUMBER: |
            PR: #${{ github.event.pull_request.number }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\":white_check_mark:\n Success Verify *${PR_NUMBER}*\n*Repository*: ${APP_NAME}\n*Author*:${PR_AUTHOR}\n*Commit/PR*:${PR_TITLE}\n*Action*:${PIPE_URL}\"}" $SLACK_WEBHOOK_URL
